### ISSUE TITLE
Instagram link broken!

### ISSUE THREAD

**Issue by BaseMax** [CameronFoxly/CameronFoxly#1]
Hello Cameron;

That link is broken: https://github.com/CameronFoxly/CameronFoxly/blob/master/www.instagram.com/wowshortfilm
and I guess the correct link is: https://www.instagram.com/wowshortfilm/

Best wishes;

**Comment by BaseMax** [comment]
Okay, I will send a PR for this issue.

**Comment by CameronFoxly** [comment]
Gah! I totally missed this when it happened and here I am over a year later finally noticing. I SO appreciate you taking the time to try an improve my page, and I'm sorry I missed it. The link is fixed now!
